- name: Clone the kin-app-service repo
  git:
    repo=https://github.com/kinfoundation/kin-app-server.git
    dest=/opt/kin-app-server
    accept_hostkey=true
    force=yes
    version={{kin_app_server_branch_name}}

- name: Template the config file
  template:
    src: templates/tippicserver/config.py.jinja2
    dest: /opt/kin-app-server/tippicserver/config.py

- name: install the kin-app-server from the local copy. force upgrade to take any changes.
  pip: 
    name: /opt/kin-app-server
    state: latest

- name: Clone the kinit-client-validation-server-module
  git:
    repo=git@github.com:kinecosystem/kinit-client-validation-server-module.git
    dest=/opt/kinit-client-validation-server-module
    accept_hostkey=true
    force=yes
    version=master
    key_file=/home/ubuntu/.ssh/id_rsa.validation_module

- name: install the kinit-client-validation-server-module  from the local copy. force upgrade to take any changes.
  pip: 
    name: /opt/kinit-client-validation-server-module 
    state: latest


- name: restart supervisor
  supervisorctl:
    name: tippicserver
    state: restarted