- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true
  roles:
    - weareinteractive.environment
    - Datadog.datadog
    - tippic-server
    - igor_mukhin.bash_aliases

  vars:
   branch_name: tippic
   deployment_env: stage
   environment_config:
     ENV: stage
     STELLAR_ACCOUNT_SID: "{{ play_hosts.index(inventory_hostname) }}" # sets the host's index within the play
   datadog_config:
     log_level: INFO
     tags: "service:tippic-server-stage"
   datadog_api_key: "{{ lookup('aws_ssm', '/config/tippic/stage/datadog/apikey' )}}"
   debug: True
   nginx_domain: stage.tippicapp.com
   db_connstr: "postgresql://{{lookup('aws_ssm', '/config/tippic/stage/sql/userpassword')}}@tippic-stage.cudbl0spntq9.us-east-1.rds.amazonaws.com/tippicdb"
   redis_endpoint: 'kin-app-server-stage.qugi0x.0001.use1.cache.amazonaws.com'
   redis_port: 6379
   stellar_timeout_sec: 30
   stellar_initial_account_balance: 2
   stellar_network: 'Kin Playground Network ; June 2018'
   stellar_kin_issuer_address: GBC3SG6NGTSZ2OMH3FFGB7UVRQWILW367U4GSOOF4TFSZONV42UJXUH7
   stellar_horizon_url: https://horizon-playground.kininfrastructure.com
   kms_key_aws_region: 'us-east-1'
   phone_verification_enabled: True
   phone_verification_required: False
   p2p_transfers_enabled: False
   p2p_min_kin_amount: 0
   p2p_max_kin_amount: 200
   auth_token_send_interval_days: 0
   auth_token_enforced: False
   auth_token_enabled: False
   payment_service_url: 'http://stage.payments.kinitapp.com:4999'
   api_server_url: 'https://stage.tippicapp.com'
   use_payment_service_phone_number_prefix: '+'
   use_payment_service_percent_of_users: 100
   block_onboarding_android_version: 1.2.5
   block_onboarding_ios_version: 1.0.0
   blocked_phone_prefixes: "['+55']"
   allowed_phone_prefixes: "['+1','+44','+972']"
   blocked_country_codes: "[]"
   max_num_registrations_per_number: 9999

   bash_aliases:
     - { alias: '_env', command: 'echo "tippicserver"' }
     - { alias: '_grep', command: 'cat /var/log/tippicserver.err.log|grep '}
     - { alias: '_grepworker-fast', command: 'cat /var/log/tippicworker_fast.err.log|grep '}
     - { alias: '_grepworker-slow', command: 'cat /var/log/tippicworker_slow.err.log|grep '}
     - { alias: '_log', command: 'cat /var/log/tippicserver.err.log' }
     - { alias: '_tail', command: 'tail -f /var/log/tippicserver.err.log -n 10' }
     - { alias: '_tailworker-fast', command: 'tail -f /var/log/tippicworker_fast.err.log -n 10' }
     - { alias: '_tailworker-slow', command: 'tail -f /var/log/tippicworker_slow.err.log -n 10' }
     - { alias: '_sql', command: "psql postgresql://{{lookup('aws_ssm', '/config/tippic/stage/sql/userpassword')}}@tippic-stage.cudbl0spntq9.us-east-1.rds.amazonaws.com/tippicdb" }

# add aliases to non-sudo user
- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: false
  roles:
    - igor_mukhin.bash_aliases

  vars:
   bash_aliases:
     - { alias: '_env', command: 'echo "tippicserver-stage"' }
     - { alias: '_grep', command: 'cat /var/log/tippicserver.err.log|grep '}
     - { alias: '_grepworker-fast', command: 'cat /var/log/tippicworker_fast.err.log|grep '}
     - { alias: '_grepworker-slow', command: 'cat /var/log/tippicworker_slow.err.log|grep '}
     - { alias: '_log', command: 'cat /var/log/tippicserver.err.log' }
     - { alias: '_tail', command: 'tail -f /var/log/tippicserver.err.log -n 10' }
     - { alias: '_tailworker-fast', command: 'tail -f /var/log/tippicworker_fast.err.log -n 10' }
     - { alias: '_tailworker-slow', command: 'tail -f /var/log/tippicworker_slow.err.log -n 10' }
     - { alias: '_sql', command: "psql postgresql://{{lookup('aws_ssm', '/config/tippic/stage/sql/userpassword')}}@tippic-stage.cudbl0spntq9.us-east-1.rds.amazonaws.com/tippicdb"}
