- name: Clone the tippic-server repo
  git:
    repo=https://github.com/kinfoundation/kin-app-server.git
    dest=/opt/tippic-server
    accept_hostkey=true
    force=yes
    version={{branch_name}}

- name: Template the config file
  template:
    src: templates/tippicserver/config.py.jinja2
    dest: /opt/tippic-server/tippicserver/config.py

- name: install the tippic-server from the local copy. force upgrade to take any changes.
  pip: 
    name: /opt/tippic-server
    state: latest

- name: restart supervisor
  supervisorctl:
    name: tippicserver
    state: restarted