- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true
  roles:
    - kin-app-server-bin

  vars:
   kin_app_server_branch_name: master
   deployment_env: stage
   environment_config: # only sets the console env, not the app context. to set the context, edit supervisor's config
     ENV: stage
     STELLAR_ACCOUNT_SID: "{{ play_hosts.index(inventory_hostname) }}" # sets the host's index within the play
   debug: True
   nginx_domain: stage2.kinitapp.com
   db_connstr: "postgresql://{{lookup('aws_ssm', '/config/stage/sql/userpassword')}}@kinappstage.cudbl0spntq9.us-east-1.rds.amazonaws.com/kinappstage"
   redis_endpoint: 'kin-app-server-stage.qugi0x.0001.use1.cache.amazonaws.com'
   redis_port: 6379
   eshu_username: admin
   eshu_password: admin
   eshu_exchange: eshu-exchange
   eshu_queue: eshu-queue
   eshu_virtual_host: kinapp
   eshu_appid: kinapp
   eshu_rabbit_address: 10.0.1.20
   stellar_timeout_sec: 30
   stellar_initial_account_balance: 2
   stellar_network: 'Kin Testnet ; December 2018'
   stellar_kin_issuer_address: GBC3SG6NGTSZ2OMH3FFGB7UVRQWILW367U4GSOOF4TFSZONV42UJXUH7
   stellar_horizon_url: https://horizon-testnet.kininfrastructure.com
   max_simultaneous_orders_per_user: 2
   kms_key_aws_region: 'us-east-1'
   phone_verification_enabled: True
   phone_verification_required: False
   p2p_transfers_enabled: False
   p2p_min_tasks: 0
   p2p_min_kin_amount: 0
   p2p_max_kin_amount: 200
   auth_token_send_interval_days: 1
   auth_token_enforced: False
   auth_token_enabled: True
   blackhawk_purchases_enabled: False
   blackhawk_critical_balance_threshold: 50
   payment_service_url: 'http://stage.payments.kinitapp.com:4999'
   api_server_url: 'https://stage2.kinitapp.com'
   use_payment_service_phone_number_prefix: '+'
   use_payment_service_percent_of_users: 100
   block_onboarding_android_version: 1.2.5
   block_onboarding_ios_version: 1.0.0
   blocked_phone_prefixes: "['+55']"
   allowed_phone_prefixes: "['+1','+44','+972']"
   blocked_country_codes: "[]"
   truex_blacklisted_taskids: "[]"
   max_num_registrations_per_number: 9999
   force_update_below_version_android: '1.0'
   force_update_below_version_ios: '1.0'
   is_update_available_below_version_android: '1.0'
   is_update_available_below_version_ios: '1.0'
   zendesk_api_token: "{{lookup('aws_ssm', '/config/stage/zendesk/apikey')}}"